#!/bin/bash

if [ $# != 1 ] ; then
    echo "Usage: `basename $0` <darwin-log-file>"
    echo "    (where <darwin-log-file> is a log file generated by EasyDarwin)"
    exit 1;
fi

log_file_name=`basename $1`
log_file=${log_file_name%.*}

echo "Processing $1 ..."

rm -f ${log_file}_*.result

grep -E "#0x[0-9a-fA-F]{12}" $1 | while read line ; do
    # combine=`echo $line | awk -F "[#\[\]]" '{print $2 $3 $5}'`
    # the combine is like "14:41:18 779 0x7f82300920f0"
    # time=${combine:0:12}
    # id=${combine:13:14}
    time=${line:1:12}
    id=${line:24:14}

    combine=${line##*: } #combine now is like "8.04 s." or "9.82s"

    #cache=`echo $line | awk -F ": " '{print $2}' | awk -F "[ s]" '{print $1}'`
    cache=${combine:0:4}

    echo "$time $cache" >> ${log_file}_${id}.result
done

grep -E "rtp packets lost" $1 | while read line ; do
    time=${line:1:12}
    id=${line:23:14}

    echo "$time $id" >> ${log_file}_${id}_lost.result
done

echo "Done."
